# Generated by Django 5.2.4 on 2026-07-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'contact message', 'verbose_name_plural': 'contact messages'},
        ),
    ]
