# Generated by Django 5.2.4 on 2026-07-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_improve_product_review_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='product_review',
            options={'ordering': ['-created_at'], 'verbose_name': 'product review', 'verbose_name_plural': 'product reviews'},
        ),
    ]
